# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  encoding: utf8
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  reconnect: false

development:
  <<: *default
  database: sai_dev
  username: root
  password:
  host: localhost

test:
  <<: *default
  database: sai_test
  username: root
  password:
  host: localhost

production:
  encoding: utf8
  adapter: mysql2
  url: <%= ENV["CLEARDB_DATABASE_URL"] %>
  timeout: 5000
  reconnect: false
